### ISSUE TITLE
Install fpp after hours problems

### ISSUE THREAD

**Issue by tripishadow** [jcrossbdn/fpp-after-hours#10]
hi, i try to install the plugin but it doesn´t work. the message that shows is 

_Installing plugin fpp-after-hours
Cloning into 'fpp-after-hours'...
fatal: unable to access 'https://github.com/jcrossbdn/fpp-after-hours.git/': Could not resolve host: github.com
chown: cannot access 'fpp-after-hours': No such file or directory

Done_

How i can install it?

Thanks

**Comment by jcrossbdn** [comment]
This is an issue with the network dns configuration on your pi so you actually won’t be able to install any plugins from the internet (or sync to a time server) until until that issue is resolved.

Please reach out to the fpp forum for support on this issue.

Thanks,
Jason

**Comment by tripishadow** [comment]
thanks. i´ll contact with the fpp forum. 

regards,

antonio

**Comment by jcrossbdn** [comment]
Sorry my comment was so short. Was a busy last few days.
If you have not got resolution to the DNS issue yet you can try setting DNS server to 8.8.8.8 in the Status/Control, Network screen in fpp.  If that does not solve the issue then further network troubleshooting will have to be done.
