### ISSUE TITLE
URL’s disappear from list when adding new station

### ISSUE THREAD

**Issue by theavguy99** [jcrossbdn/fpp-after-hours#11]
FPP V4.5.1
Several times now when I add a new internet radio station and hit save, the list will reload and all the URL’s will be blank.

**Comment by jcrossbdn** [comment]
@theavguy99 Can you provide the following file contents:

/home/fpp/media/plugindata/fpp-after-hours-config.history
/home/fpp/media/plugindata/fpp-after-hours-config.json

**Comment by theavguy99** [comment]
See attached.
Here's how it reads in the UI:


Michael Redman, Systems Integration Specialist             

AVIXA CTS#1326538
Crestron Certified Silver Master Programmer,
DMC-D, T, E-4K, DM-NVX-N



Design + Integration + Service
Professional Audio & Video Systems

110 Wall Williams Rd.
West Monroe, LA 71291
318.372.8664 
theavguy99@yahoo.com 

    On Wednesday, January 13, 2021, 10:43:48 PM CST, Jason Cross <notifications@github.com> wrote:  
 
 


@theavguy99 Can you provide the following file contents:

/home/fpp/media/plugindata/fpp-after-hours-config.history
/home/fpp/media/plugindata/fpp-after-hours-config.json

**Comment by theavguy99** [comment]
Also wanted to ask, is there a way to add a streaming 'watchdog' that will check for stream activity every couple of minutes and attempt to restart the stream if the stream has dropped?
Some streams I've found are very consistent, while others will stream for several hours and stop- then have to be manually restarted to continue.
Currently as a work around for this, once a day in scheduler I have a schedule entry to stop the stream and then a few seconds later restart.
Michael Redman, Systems Integration Specialist             

AVIXA CTS#1326538
Crestron Certified Silver Master Programmer,
DMC-D, T, E-4K, DM-NVX-N



Design + Integration + Service
Professional Audio & Video Systems

110 Wall Williams Rd.
West Monroe, LA 71291
318.372.8664 
theavguy99@yahoo.com 

    On Thursday, January 14, 2021, 07:09:37 AM CST, Michael Redman <theavguy99@yahoo.com> wrote:  
 
 See attached.
Here's how it reads in the UI:


Michael Redman, Systems Integration Specialist             

AVIXA CTS#1326538
Crestron Certified Silver Master Programmer,
DMC-D, T, E-4K, DM-NVX-N



Design + Integration + Service
Professional Audio & Video Systems

110 Wall Williams Rd.
West Monroe, LA 71291
318.372.8664 
theavguy99@yahoo.com 

    On Wednesday, January 13, 2021, 10:43:48 PM CST, Jason Cross <notifications@github.com> wrote:  
 
 


@theavguy99 Can you provide the following file contents:

/home/fpp/media/plugindata/fpp-after-hours-config.history
/home/fpp/media/plugindata/fpp-after-hours-config.json

**Comment by jcrossbdn** [comment]
Haven’t looked into your original issue yet but plan to next week once things slow down here.

There is a cron entry that is engaged upon install that will restart if a stream completely fails.  I have to check on what other failed streams look like and if there is a way I can detect it then it could be corrected in this script.

Can you send me the URL for a few that you have had the most issues with so I can see how they fail and what mpd reports once they have failed.

Jason
