### ISSUE TITLE
Its asking to upgrade and it dosent do anything.

### ISSUE THREAD

**Issue by waycool5794** [jcrossbdn/fpp-after-hours#12]
![afterhours](https://user-images.githubusercontent.com/94303062/141685841-c74cac05-54aa-4fff-9c58-beccc96ec65f.jpg)

it never updates

**Comment by jcrossbdn** [comment]
Was this from a fresh fpp image or did you do the upgrade from 4 to 5?

Jason

**Comment by waycool5794** [comment]
From a fresh start of FPP5.0 with updates to FPP5.3

Installed after hours and first thing it needs to do is an update but
doesn't seem to so anything. Its says to reboot after installation but its
not doing anything.

Thanks,
Greg S.

CONFIDENTIALITY NOTICE: This email, including any attachments, is
confidential and this content may not be shared, copied or retransmitted to
any other party. If you are not the intended recipient please notify the
sender immediately, and please delete it; you should not copy it or use it
for any purpose or disclose its contents to any other person

**Comment by jcrossbdn** [comment]
I was only able to replicate this behaviour once and a reboot solved it.  Just checking if you have rebooted recently?

If you have then we will likely have to step through the permissions on the directories to see what is happening.

Jason

**Comment by ckuhner** [comment]
I’m having the same issue. Install the plug in and then click to download content. Reboot and still asks to download extra content. Even tried downloading from the FPP shell and rebooted but it’s still asking for the extra content and not allowing for any set up. 

Just discovered I’m still on 4. Upgrading to 5 and will try again.

**Comment by jcrossbdn** [comment]
@ckuhner We did figure out that some of the FPP OS images have an issue that need manual correction.  Can you try the following:
1) from the pi/bbb you want to run fpp after hours from click on Help and then SSH Shell.
2) login with username: fpp  and password: falcon
3) type in sudo apt install mpd mpc

If the text below says "E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem" then please type in "sudo dpkg --configure -a" and follow any prompts that come up.

Assuming at the end of this there are no futher errors reported you should be able to run the install from the fpp-after-hours plugin again and it should work.  Please report if there are other errors or such so they can be passed onto the appropriate dev teams.

If this solves it for you also then I will add this to the plugin documentation.  Also please identify what type of device you have and what version.  We had previously seen this on a bbb with v5.4.1
