### ISSUE TITLE
Need to continually hit "Start Script" after a certain period time

### ISSUE THREAD

**Issue by rci27** [jcrossbdn/fpp-after-hours#13]
I am having an issue which is hard to diagnose.  I am using FPP 5.5 and running the latest version of the plug in. I run "Start Script" and music plays as normal as I am listening in the car.  After a short time, and it always seems to be when I am not listening, the music will stop.  I have no playlists, or schedules, or commands active.  I can run "Start Script" to start the music again.  It cannot pinpoint when or why the music keeps stopping.

**Comment by jcrossbdn** [comment]
I'm still waiting for the URL that you are experiencing the issue with so I can test.  Closing this ticket for now.
