### ISSUE TITLE
Is there a way to edit the connection retry attempt window?

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#15]
If I understand the documentation and how this is set up, this plugin will attempt to reconnect to a stream should it be interrupted for several reasons. I tested that and was successful with a short outage, but noticed that during an extended timeout to a stream that I was re-starting (I own the streaming service) that it did not reconnect. I'm trying to figure out if there is a way to edit the connection retry attempt window, and also, what is the window before it gives up as built? Thanks!

**Comment by jcrossbdn** [comment]
Can you do another test where you start the stream, run the "mpc" command, and then forcibly kill it and run the command a few more times.

The after hours plugin runs the command "mpc" and then looks for the response to start with [playing] # and if it finds that then it figures the stream is still running.

I'd be interested to know if there is additional info that shows up on that commands response to help us better determine if there is a fault and the stream needs to be restarted.

e.g. Here is what mine shows right now:
fpp@Master:/ $ mpc
Radio X-MAS: Jose Feliciano - Feliz Navidad
[playing] #1/1   0:54/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off


so things like the counter stopping or the name being blank are possible items that would be parsable.  Seeing this entire data structure from your setup would be beneficial if you wanted to copy/paste it in it's entirety as you are testing.

**Comment by nmiller0113** [comment]
@jcrossbdn, I think I did what you requested. I started the stream, ran the mpc command and got this:
fpp@fpptest:~ $ mpc
The Miller Lights: Boyz II Men - Silent Night
[playing] #1/1   0:42/0:00 (0%)
volume:100%   repeat: off   random: off   single: off   consume: off

Then I shut the stream down and ran the mpc command and got this:
fpp@fpptest:~ $ mpc
volume:100%   repeat: off   random: off   single: off   consume: off

I also saw "IP is not pingable" in the interface since I shutdown the server. When the server was brought back online a few mins later, the stream never recovered on FPP.

I then ran another test and just rebooted the streaming server; the same result in the mpc and interface messages, but this time it recovered in FPP. This is what led me to believe that it's related to a timeout. The reboot was less than 30 seconds (it's a container), and when I shut it down in the previous test, it was offline for more than a couple of minutes.

I'm running this in a test instance of FPP so I'm happy to provide you whatever other info you need. You mentioned sharing the entire data structure, can you please let me know what you're referring to specifically and where to find it? I'll be happy to post it here. Thanks again!

**Comment by nmiller0113** [comment]
@jcrossbdn not sure if you've seen my previous message yet, but I went ahead and spun up a new fpp test instance and ran the install to see if there were any errors. Not sure if this is important, or relevant, but I'll copy the output from the install below. Notice the "Job failed. See "journalctl -xe" for details." at the very bottom:

! ! ! Software Installation Report ! ! !
Hit:1 http://deb.debian.org/debian bullseye-backports InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
javascript-common libadplug-2.3.3-0 libaudiofile1 libbinio1v5 libfaad2
libfluidsynth2 libid3tag0 libinstpatch-1.0-2 libiso9660-11 libixml10
libjs-jquery libjs-sphinxdoc libjs-underscore libmad0 libmikmod3 libmms0
libmodplug1 libmpcdec6 libmpdclient2 libnfs13 libshout3 libsidplayfp5
libsmbclient libupnp13 libwildmidi2 libyajl2 libzzip-0-13 timgm6mb-soundfont
Suggested packages:
adplug-utils sidplayfp libwildmidi-config icecast2 pulseaudio
fluid-soundfont-gm
The following NEW packages will be installed:
javascript-common libadplug-2.3.3-0 libaudiofile1 libbinio1v5 libfaad2
libfluidsynth2 libid3tag0 libinstpatch-1.0-2 libiso9660-11 libixml10
libjs-jquery libjs-sphinxdoc libjs-underscore libmad0 libmikmod3 libmms0
libmodplug1 libmpcdec6 libmpdclient2 libnfs13 libshout3 libsidplayfp5
libsmbclient libupnp13 libwildmidi2 libyajl2 libzzip-0-13 mpc mpd
timgm6mb-soundfont
0 upgraded, 30 newly installed, 0 to remove and 47 not upgraded.
Need to get 8878 kB of archives.
After this operation, 15.5 MB of additional disk space will be used.
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libsmbclient armhf 2:4.13.13+dfsg-1~deb11u4 [162 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libbinio1v5 armhf 1.5+dfsg-0.1 [22.6 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libadplug-2.3.3-0 armhf 2.3.3+dfsg-2 [189 kB]
Get:4 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libaudiofile1 armhf 0.3.6-5 [95.9 kB]
Get:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libfaad2 armhf 2.10.0-1 [146 kB]
Get:6 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libinstpatch-1.0-2 armhf 1.1.6-1 [213 kB]
Get:7 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf timgm6mb-soundfont all 1.3-5 [5427 kB]
Get:8 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libfluidsynth2 armhf 2.1.7-1.1 [192 kB]
Get:9 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libid3tag0 armhf 0.15.1b-14 [29.9 kB]
Get:10 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libiso9660-11 armhf 2.1.0-2 [165 kB]
Get:11 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libixml10 armhf 1:1.8.4-2 [73.6 kB]
Get:12 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libmad0 armhf 0.15.1b-10 [66.0 kB]
Get:13 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libmikmod3 armhf 3.3.11.1-6 [119 kB]
Get:14 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libmms0 armhf 0.6.4-3 [33.8 kB]
Get:15 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libmodplug1 armhf 1:0.8.9.0-3 [146 kB]
Get:16 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libmpcdec6 armhf 2:0.1~r495-2 [31.1 kB]
Get:17 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libmpdclient2 armhf 2.19-1 [38.5 kB]
Get:18 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libnfs13 armhf 4.0.0-1 [85.2 kB]
Get:19 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libshout3 armhf 2.4.5-1 [48.5 kB]
Get:20 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libsidplayfp5 armhf 2.0.5-2 [107 kB]
Get:21 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libupnp13 armhf 1:1.8.4-2 [127 kB]
Get:22 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libwildmidi2 armhf 0.4.3-1 [56.4 kB]
Get:23 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libyajl2 armhf 2.1.0-3 [20.9 kB]
Get:24 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libzzip-0-13 armhf 0.13.62-3.3+deb11u1 [52.0 kB]
Get:25 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libjs-jquery all 3.5.1+dfsg+~3.5.5-7 [315 kB]
Get:26 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libjs-underscore all 1.9.1~dfsg-3 [100 kB]
Get:27 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf libjs-sphinxdoc all 3.4.3-2 [127 kB]
Get:28 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf mpd armhf 0.22.6-1 [645 kB]
Get:29 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf javascript-common all 11+nmu1 [6260 B]
Get:30 http://mirrors.ocf.berkeley.edu/raspbian/raspbian bullseye/main armhf mpc armhf 0.33-1 [36.1 kB]
Fetched 8878 kB in 13s (693 kB/s)
Selecting previously unselected package libsmbclient:armhf.
(Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 108145 files and directories currently installed.)
Preparing to unpack .../00-libsmbclient_2%3a4.13.13+dfsg-1~deb11u4_armhf.deb ...
Unpacking libsmbclient:armhf (2:4.13.13+dfsg-1~deb11u4) ...
Selecting previously unselected package libbinio1v5:armhf.
Preparing to unpack .../01-libbinio1v5_1.5+dfsg-0.1_armhf.deb ...
Unpacking libbinio1v5:armhf (1.5+dfsg-0.1) ...
Selecting previously unselected package libadplug-2.3.3-0.
Preparing to unpack .../02-libadplug-2.3.3-0_2.3.3+dfsg-2_armhf.deb ...
Unpacking libadplug-2.3.3-0 (2.3.3+dfsg-2) ...
Selecting previously unselected package libaudiofile1:armhf.
Preparing to unpack .../03-libaudiofile1_0.3.6-5_armhf.deb ...
Unpacking libaudiofile1:armhf (0.3.6-5) ...
Selecting previously unselected package libfaad2:armhf.
Preparing to unpack .../04-libfaad2_2.10.0-1_armhf.deb ...
Unpacking libfaad2:armhf (2.10.0-1) ...
Selecting previously unselected package libinstpatch-1.0-2:armhf.
Preparing to unpack .../05-libinstpatch-1.0-2_1.1.6-1_armhf.deb ...
Unpacking libinstpatch-1.0-2:armhf (1.1.6-1) ...
Selecting previously unselected package timgm6mb-soundfont.
Preparing to unpack .../06-timgm6mb-soundfont_1.3-5_all.deb ...
Unpacking timgm6mb-soundfont (1.3-5) ...
Selecting previously unselected package libfluidsynth2:armhf.
Preparing to unpack .../07-libfluidsynth2_2.1.7-1.1_armhf.deb ...
Unpacking libfluidsynth2:armhf (2.1.7-1.1) ...
Selecting previously unselected package libid3tag0:armhf.
Preparing to unpack .../08-libid3tag0_0.15.1b-14_armhf.deb ...
Unpacking libid3tag0:armhf (0.15.1b-14) ...
Selecting previously unselected package libiso9660-11:armhf.
Preparing to unpack .../09-libiso9660-11_2.1.0-2_armhf.deb ...
Unpacking libiso9660-11:armhf (2.1.0-2) ...
Selecting previously unselected package libixml10:armhf.
Preparing to unpack .../10-libixml10_1%3a1.8.4-2_armhf.deb ...
Unpacking libixml10:armhf (1:1.8.4-2) ...
Selecting previously unselected package libmad0:armhf.
Preparing to unpack .../11-libmad0_0.15.1b-10_armhf.deb ...
Unpacking libmad0:armhf (0.15.1b-10) ...
Selecting previously unselected package libmikmod3:armhf.
Preparing to unpack .../12-libmikmod3_3.3.11.1-6_armhf.deb ...
Unpacking libmikmod3:armhf (3.3.11.1-6) ...
Selecting previously unselected package libmms0:armhf.
Preparing to unpack .../13-libmms0_0.6.4-3_armhf.deb ...
Unpacking libmms0:armhf (0.6.4-3) ...
Selecting previously unselected package libmodplug1:armhf.
Preparing to unpack .../14-libmodplug1_1%3a0.8.9.0-3_armhf.deb ...
Unpacking libmodplug1:armhf (1:0.8.9.0-3) ...
Selecting previously unselected package libmpcdec6:armhf.
Preparing to unpack .../15-libmpcdec6_2%3a0.1~r495-2_armhf.deb ...
Unpacking libmpcdec6:armhf (2:0.1~r495-2) ...
Selecting previously unselected package libmpdclient2:armhf.
Preparing to unpack .../16-libmpdclient2_2.19-1_armhf.deb ...
Unpacking libmpdclient2:armhf (2.19-1) ...
Selecting previously unselected package libnfs13:armhf.
Preparing to unpack .../17-libnfs13_4.0.0-1_armhf.deb ...
Unpacking libnfs13:armhf (4.0.0-1) ...
Selecting previously unselected package libshout3:armhf.
Preparing to unpack .../18-libshout3_2.4.5-1_armhf.deb ...
Unpacking libshout3:armhf (2.4.5-1) ...
Selecting previously unselected package libsidplayfp5:armhf.
Preparing to unpack .../19-libsidplayfp5_2.0.5-2_armhf.deb ...
Unpacking libsidplayfp5:armhf (2.0.5-2) ...
Selecting previously unselected package libupnp13:armhf.
Preparing to unpack .../20-libupnp13_1%3a1.8.4-2_armhf.deb ...
Unpacking libupnp13:armhf (1:1.8.4-2) ...
Selecting previously unselected package libwildmidi2:armhf.
Preparing to unpack .../21-libwildmidi2_0.4.3-1_armhf.deb ...
Unpacking libwildmidi2:armhf (0.4.3-1) ...
Selecting previously unselected package libyajl2:armhf.
Preparing to unpack .../22-libyajl2_2.1.0-3_armhf.deb ...
Unpacking libyajl2:armhf (2.1.0-3) ...
Selecting previously unselected package libzzip-0-13:armhf.
Preparing to unpack .../23-libzzip-0-13_0.13.62-3.3+deb11u1_armhf.deb ...
Unpacking libzzip-0-13:armhf (0.13.62-3.3+deb11u1) ...
Selecting previously unselected package libjs-jquery.
Preparing to unpack .../24-libjs-jquery_3.5.1+dfsg+~3.5.5-7_all.deb ...
Unpacking libjs-jquery (3.5.1+dfsg+~3.5.5-7) ...
Selecting previously unselected package libjs-underscore.
Preparing to unpack .../25-libjs-underscore_1.9.1~dfsg-3_all.deb ...
Unpacking libjs-underscore (1.9.1~dfsg-3) ...
Selecting previously unselected package libjs-sphinxdoc.
Preparing to unpack .../26-libjs-sphinxdoc_3.4.3-2_all.deb ...
Unpacking libjs-sphinxdoc (3.4.3-2) ...
Selecting previously unselected package mpd.
Preparing to unpack .../27-mpd_0.22.6-1_armhf.deb ...
Unpacking mpd (0.22.6-1) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../28-javascript-common_11+nmu1_all.deb ...
Unpacking javascript-common (11+nmu1) ...
Selecting previously unselected package mpc.
Preparing to unpack .../29-mpc_0.33-1_armhf.deb ...
Unpacking mpc (0.33-1) ...
Setting up libaudiofile1:armhf (0.3.6-5) ...
Setting up javascript-common (11+nmu1) ...
apache2_invoke: Enable configuration javascript-common
Setting up libmodplug1:armhf (1:0.8.9.0-3) ...
Setting up libbinio1v5:armhf (1.5+dfsg-0.1) ...
Setting up libiso9660-11:armhf (2.1.0-2) ...
Setting up libmikmod3:armhf (3.3.11.1-6) ...
Setting up libyajl2:armhf (2.1.0-3) ...
Setting up libzzip-0-13:armhf (0.13.62-3.3+deb11u1) ...
Setting up libnfs13:armhf (4.0.0-1) ...
Setting up libsidplayfp5:armhf (2.0.5-2) ...
Setting up libmpcdec6:armhf (2:0.1~r495-2) ...
Setting up libmms0:armhf (0.6.4-3) ...
Setting up libid3tag0:armhf (0.15.1b-14) ...
Setting up libixml10:armhf (1:1.8.4-2) ...
Setting up libfaad2:armhf (2.10.0-1) ...
Setting up libshout3:armhf (2.4.5-1) ...
Setting up libmpdclient2:armhf (2.19-1) ...
Setting up libsmbclient:armhf (2:4.13.13+dfsg-1~deb11u4) ...
Setting up libmad0:armhf (0.15.1b-10) ...
Setting up libwildmidi2:armhf (0.4.3-1) ...
Setting up libjs-jquery (3.5.1+dfsg+~3.5.5-7) ...
Setting up timgm6mb-soundfont (1.3-5) ...
update-alternatives: using /usr/share/sounds/sf2/TimGM6mb.sf2 to provide /usr/share/sounds/sf2/default-GM.sf2 (default-GM.sf2) in auto mode
update-alternatives: using /usr/share/sounds/sf2/TimGM6mb.sf2 to provide /usr/share/sounds/sf3/default-GM.sf3 (default-GM.sf3) in auto mode
Setting up libadplug-2.3.3-0 (2.3.3+dfsg-2) ...
Setting up libinstpatch-1.0-2:armhf (1.1.6-1) ...
Setting up libjs-underscore (1.9.1~dfsg-3) ...
Setting up libupnp13:armhf (1:1.8.4-2) ...
Setting up mpc (0.33-1) ...
Setting up libjs-sphinxdoc (3.4.3-2) ...
Setting up libfluidsynth2:armhf (2.1.7-1.1) ...
Setting up mpd (0.22.6-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/mpd.service -> /lib/systemd/system/mpd.service.
Created symlink /etc/systemd/system/sockets.target.wants/mpd.socket -> /lib/systemd/system/mpd.socket.
Job failed. See "journalctl -xe" for details.
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u4) ...

**Comment by nmiller0113** [comment]
Some other data you may find useful:

Here's my log file...every time is show "player: played "http://192.168.254.103:8000/lights"" is after I had restarted or shut off the server it was contacting. But there are some other log messages you may find interesting. One other thing to note is that it doesn't log any differently when it does recover during a reboot than when it doesn't during a longer server shutdown:

fpp@fpptest:/etc $ cat /var/log/mpd/mpd.log
Nov 02 13:20 : exception: Failed to open '/var/lib/mpd/state': No such file or directory
Nov 02 13:20 : avahi: Service 'Music Player @ fpptest' successfully established.
Nov 02 13:24 : avahi: Client Disconnected, will reconnect shortly
Nov 02 13:24 : zeroconf: No global port, disabling zeroconf
Nov 02 13:47 : zeroconf: No global port, disabling zeroconf
Nov 02 13:47 : config: option 'bitrate' on line 7 was not recognized
Nov 02 13:47 : config: option 'bitrate' on line 15 was not recognized
Nov 02 13:49 : player: played "http://192.168.254.103:8000/lights"
Nov 02 13:53 : zeroconf: No global port, disabling zeroconf
Nov 02 13:53 : config: option 'bitrate' on line 7 was not recognized
Nov 02 13:53 : config: option 'bitrate' on line 15 was not recognized
Nov 02 13:54 : player: played "http://192.168.254.103:8000/lights"
Nov 02 13:59 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:02 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:06 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:12 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:15 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:20 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:21 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:25 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:31 : player: played "http://192.168.254.103:8000/lights"

During a server reboot the state file will show the following:
fpp@fpptest:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: play
current: 0
time: 234.953000
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
song_begin: http://192.168.254.103:8000/lights
Title: Sammy Davis, Jr. - Christmas Time All Over The World
Name: The Miller Lights
song_end

But during a longer term server shutdown it starts in this state:
fpp@fpptest:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: stop
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
song_begin: http://192.168.254.103:8000/lights
Title: Train - Joy To The World
Name: The Miller Lights
song_end
playlist_end

And then moves to this and never recovers:
fpp@fpptest:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: stop
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
playlist_end

**Comment by jcrossbdn** [comment]
Thanks! I’ll dig through this later on tonight.JasonSent from my iPhoneOn Nov 2, 2022, at 4:40 PM, Nathan MIller ***@***.***> wrote:﻿
Some other data you may find useful:
Here's my log file...every time is show "player: played "http://192.168.254.103:8000/lights"" is after I had restarted or shut off the server it was contacting. But there are some other log messages you may find interesting. One other thing to note is that it doesn't log any differently when it does recover during a reboot than when it doesn't during a longer server shutdown:
***@***.***:/etc $ cat /var/log/mpd/mpd.log
Nov 02 13:20 : exception: Failed to open '/var/lib/mpd/state': No such file or directory
Nov 02 13:20 : avahi: Service 'Music Player @ fpptest' successfully established.
Nov 02 13:24 : avahi: Client Disconnected, will reconnect shortly
Nov 02 13:24 : zeroconf: No global port, disabling zeroconf
Nov 02 13:47 : zeroconf: No global port, disabling zeroconf
Nov 02 13:47 : config: option 'bitrate' on line 7 was not recognized
Nov 02 13:47 : config: option 'bitrate' on line 15 was not recognized
Nov 02 13:49 : player: played "http://192.168.254.103:8000/lights"
Nov 02 13:53 : zeroconf: No global port, disabling zeroconf
Nov 02 13:53 : config: option 'bitrate' on line 7 was not recognized
Nov 02 13:53 : config: option 'bitrate' on line 15 was not recognized
Nov 02 13:54 : player: played "http://192.168.254.103:8000/lights"
Nov 02 13:59 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:02 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:06 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:12 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:15 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:20 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:21 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:25 : player: played "http://192.168.254.103:8000/lights"
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:28 : alsa_output: Decoder is too slow; playing silence to avoid xrun
Nov 02 14:31 : player: played "http://192.168.254.103:8000/lights"
During a server reboot the state file will show the following:
***@***.***:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: play
current: 0
time: 234.953000
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
song_begin: http://192.168.254.103:8000/lights
Title: Sammy Davis, Jr. - Christmas Time All Over The World
Name: The Miller Lights
song_end
But during a longer term server shutdown it starts in this state:
***@***.***:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: stop
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
song_begin: http://192.168.254.103:8000/lights
Title: Train - Joy To The World
Name: The Miller Lights
song_end
playlist_end
And then moves to this and never recovers:
***@***.***:/etc $ cat /var/lib/mpd/state
sw_volume: 100
audio_device_state:1:bcm2835 ALSA
audio_device_state:0:bcm2835 HDMI 1
state: stop
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
playlist_end

**Comment by jcrossbdn** [comment]
I've made a couple of updates that I hope will solve it, if not then I will have to parse the mpd state directly.

It will now ping the station when the cron runs to see if the music is still playing and if the ping fails will re-run the start script to either try to reload it or to pick another available station.

Also I removed the "Source" checkbox since it actually doesn't do anything at this moment.  It was put there so that you could choose between local audio or internet streams but since the local controls are not written yet I removed the checkbox and the entire tab.

If you can update and run a few more tests on the stream failure handling that would be fantastic!

**Comment by nmiller0113** [comment]
Thanks for all the work @jcrossbdn! Unfortunately, it still doesn't work if the server is down for an extended period. I first tried 5m, then 2m, and both times it did not recover. I also tried a reboot which is ~30s down, and it recovered.

On a side note, the cleanup of the interface looks good! Sorry I didn't have better news for the other part! Please let me know what I can do to test. Happy to help and appreciate your efforts!

**Comment by jcrossbdn** [comment]
ok, I've looked at /var/lib/mpd/state and that file is not updated enough to be useful (I'm seeing it take up to a minute to update at times).

Could you run your same tests again but show the output of "mpc current".  I'm trying to find something that will accurately detect (from mpc/mpd) when the stream has broken and the timeout has expired.  I see no configuration options in /etc/mpd.conf and am not 100% confident that mpc current won't return a blank under some normal conditions.

**Comment by nmiller0113** [comment]
@jcrossbdn, I tested it just now, and the moment I break the stream in any way mpc current goes blank. I hope that was helpful. In my opinion, the state file should really track whether the stream should be playing or not and it should maintain the "running" state until the stop script tells it to stop. So even if the stream stops for any reason, no matter how long, as long as the state is "running" it should keep retrying to connect/re-establish the session. I know you aren't the mpd creator, but this seems like something simple it should be able to do since it is clearly aware when it breaks...as shown by the mpc current going blank immediately.

**Comment by jcrossbdn** [comment]
Blank with a newline?A screenshot would be very helpful:)JasonSent from my iPhoneOn Nov 6, 2022, at 3:29 PM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn, I tested it just now, and the moment I break the stream in any way mpc current goes blank. I hope that was helpful. In my opinion, the state file should really track whether the stream should be playing or not and it should maintain the "running" state until the stop script tells it to stop. So even if the stream stops for any reason, no matter how long, as long as the state is "running" it should keep retrying to connect/re-establish the session. I know you aren't the mpd creator, but this seems like something simple it should be able to do since it is clearly aware when it breaks...as shown by the mpc current going blank immediately.

**Comment by nmiller0113** [comment]
Here you go @jcrossbdn. This screenshot is before and after a basic reboot. I hope this answers your question.

<img width="563" alt="Screen Shot 2022-11-06 at 3 34 21 PM" src="https://user-images.githubusercontent.com/1048868/200201581-ec1c2b01-8957-434c-af36-003d74c80a06.png">

**Comment by nmiller0113** [comment]
Hello again @jcrossbdn, just checking whether you've had any luck or just not had time to look at this again. Thank you!

**Comment by jcrossbdn** [comment]
My apologies, haven’t had time to get back to it yet.  Trying to get my display up and runningJasonSent from my iPhoneOn Nov 28, 2022, at 5:40 PM, Nathan MIller ***@***.***> wrote:﻿
Hello again @jcrossbdn, just checking whether you've had any luck or just not had time to look at this again. Thank you!

**Comment by nmiller0113** [comment]
@jcrossbdn, no worries or need to apologize. I figured as much and was only checking in! Thanks again! I hope you had a great Thanksgiving and your display is coming together successfully!

**Comment by iamwally** [comment]
I am also very interested in this issue as I love to run the after hours plugin but I have noticed that it runs for a while and then shutdown.  I assume because of interruptions in the stream.  I am following this conversation and would be glad to help if there is anything I can add.

**Comment by jcrossbdn** [comment]
@nmiller0113 & @iamwally I took a break from sequencing tonight to get this fixed up.  You should be able to upgrade from the plugin page and hopefully this now resolves the issues.  Note it can take up to 70 seconds for a disrupted stream to be noticed since the cron that checks only runs once a minute.  Once a stream has been noticed to be down it will also show on the plugin page that restarts are actively taking place.

Please let me know if this does not resolve the issue for you.  I have tested it for the last hour or so by telling my firewall to prevent my pi from accessing the internet for several minutes at a time and it is now consistently restarting the stream once it is available again.  I have also removed some code that was improperly telling the plugin that music should not be running when there were no pingable sources.

Jason

**Comment by nmiller0113** [comment]
@jcrossbdn I just had a chance to test it and shut it down for about 15 mins, and it reconnected with absolutely no problem! I think it's fixed now! Nice work! Thank you again for all your effort here; it's appreciated!

I'm going to close this since it's resolved, but I had a question regarding the Now Playing status...what do the following mean?

repeat: off random: off single: off consume: off

Is that just stuff left over from the local media option?

**Comment by jcrossbdn** [comment]
Fantastic!Yes that line is just what is returned from the mpd program that actually plays the music.  I didn’t feel it necessary to remove:)JasonSent from my iPhoneOn Dec 4, 2022, at 2:01 PM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn I just had a chance to test it and shut it down for about 15 mins, and it reconnected with absolutely no problem! I think it's fixed now! Nice work! Thank you again for all your effort here; it's appreciated!
I'm going to close this since it's resolved, but I had a question regarding the Now Playing status...what do the following mean?
repeat: off random: off single: off consume: off
Is that just stuff left over from the local media option?
