### ISSUE TITLE
Send to Vast FM Transmitter plugin for RDS (Feature request)

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#16]
I'm running a Vast FM Transmitter with the Si4713/Vast V-FMT212R plugin with RDS. It would be awesome for this plugin to be able to send song data in RDS like it does when my sequences play. I'm assuming it's possible, I'm just not sure how. The After Hours Plugin has an awareness of song titles and artists, all it would have to do is send it to the Vast plugin. I'm not even sure if that's a thing that's possible...but I had to ask :) Thanks!

**Comment by jcrossbdn** [comment]
I took a look at the vast plugin and it is deeply rooted into the C++ library of fpp to receive song titles and start/stop based on playlists.  A request would have to be submitted to the plugins maintainers to possibly add additional functionality to their plugin.  If they are willing to make the changes then I would be willing to make this update in fpp-after-hours.

They may have better ideas, however, off the top of my head if there was an option to "read rds from file" when there is no fpp playlist running that may be a reasonable solution.  It would allow any plugin to push rds data using the vast plugin.  Data could be presented either formatted with a hyphen already as artist - title or artist on line1 and title on line 2 or json data (and so on).

**Comment by nmiller0113** [comment]
Thanks @jcrossbdn, I'll check into it! I appreciate the response!
