### ISSUE TITLE
Local Media

### ISSUE THREAD

**Issue by iamwally** [jcrossbdn/fpp-after-hours#18]
Will the local media feature be added at some point?

Thank you

**Comment by jcrossbdn** [comment]
@iamwally yeah this is on the roadmap but I likely won't get to it for this season.  I have to figure out the best way to organize and push files at mpd.  It hasn't been a highly requested feature as most people use internet radio streams so unfortunately it keeps getting pushed down the priority list.

**Comment by nmiller0113** [comment]
@iamwally you're more than welcome to use our stream if you'd like. It's http://stream.themillerhome.org:8000/lights and it's got over 20 hours of holiday season music!

You can also go to https://radio.themillerhome.org/public/the_miller_lights and make song requests, if you'd like, to play your favorites :)

**Comment by iamwally** [comment]
Thanks!!! I will definitely check it out!!!

**Comment by jcrossbdn** [comment]
Closing for now until I determine how to best implement this and write the code.
