### ISSUE TITLE
Dependency failure requiring reboot - intermittent

### ISSUE THREAD

**Issue by jcrossbdn** [jcrossbdn/fpp-after-hours#19]
Intermittently in v6.1 and 6.2 some are seeing where the plugin page will show "Dependencies are not loaded" (after the plugin has been installed and running for some time) and the show may not start properly.

I am pushing an update to the plugin to attempt to capture data that is needed for troubleshooting

**Comment by bcarriveau** [comment]
can confirm it seems to install on Pis with no issue and really doesn't want to install on the BB devices that are even running 5.5.26.

**Comment by nmiller0113** [comment]
I'm still having zero issues on 2 BBB's all running 6.2 fresh installs. I've not updated to your newer version yet.

**Comment by jcrossbdn** [comment]
> 

Interesting, I haven't tested it on a BB device in a number of years.  Can you provide more detail about what is failing when trying to install on BB?  I do have a BBB controlling my tune to sign but don't want to mess with it while the show is in production as it's way up in the air and if it comes in it will have to sit for hours to thaw out.

**Comment by jcrossbdn** [comment]
I had the issue happen to me tonight and was able to look at logs and such.  Unfortunately it is something inside of mpd that is locking up and I was unable to correct it without performing a reboot as the port would not release and killing mpd's process would not restore functionality.

![image](https://user-images.githubusercontent.com/10160178/210457054-78f5de66-d261-4e50-936e-dd1a7e3ca683.png)

I located a reference to this issue at https://github.com/MusicPlayerDaemon/MPD/issues/1263 and have implemented the solution presented in that post (buffer_time "200000" & period_time "5084") and will test once my show is done tonight before pushing this update to git.

Also determined that the resultset from exec in the fah plugin does not return any useful data so will also remove this logging from the fah plugin as it just ends up filling up the log file with useless data.

**Comment by jcrossbdn** [comment]
No success with the buffer and period time settings. 

Added an attempt to restart the mpd service when dependencies are not found but it seems hit and miss.

**Comment by nmiller0113** [comment]
@jcrossbdn, not that this is helpful to the issue you're troubleshooting, but my install has continued to be rock solid on a bbb and running for weeks without issue.

**Comment by jcrossbdn** [comment]
I am glad to hear that :)JasonSent from my iPhoneOn Jan 4, 2023, at 3:31 PM, Nathan MIller ***@***.***> wrote:﻿
@jcrossbdn, not that this is helpful to the issue you're troubleshooting, but my install has continued to be rock solid on a bbb and running for weeks without issue.

**Comment by jcrossbdn** [comment]
Haven't seen this issue in a year, closing.
