### ISSUE TITLE
Dynamic Enable checkboxes

### ISSUE THREAD

**Issue by LightsOnHudson** [jcrossbdn/fpp-after-hours#2]
The Active checkbox in the list could benefit from being dynamically and taking advantage of the bubble pop ups telling the user they have made it Active. 

Save config is after a lot of changes, but I didn't know to check the Active box, and then click save. 

Additionally, You have the option to have a /help/ folder where a user can press F1 or the Help within a plugin to read any documentation you want on how to set it up.

**Comment by jcrossbdn** [comment]
I would like to make the entire UI dynamic but that will have to be a future project.

The help directory was not immediately working for me so decided to put that off for future.  I would also like to allow inline popups to display help for specific inputs.

**Comment by jcrossbdn** [comment]
This is still on my list of todo's as the plugin's entire UI needs to be brought up to 6.x UI standards.

**Comment by jcrossbdn** [comment]
This has been completed in the new UI just released
