### ISSUE TITLE
Can't Finish Install of AHMP

### ISSUE THREAD

**Issue by coachbindel** [jcrossbdn/fpp-after-hours#21]
I've run the "install" many times, and I never get past the page that installs "sudo apt-get -y update && sudo apt-get -y install mpd mpc".

It usually takes to me to the next page and says:

Hit:1 http://deb.debian.org/debian bullseye-backports InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...

and nothing else happens. I've done it many times over the last few days. Please help.

**Comment by jcrossbdn** [comment]
Inside the fpp interface can you go to help and then ssh shell and try typing the commands in manually.  I have seen the issue you are having a few times and this has always solved it so far.

sudo apt update

sudo apt upgrade -y

sudo apt install -y mpd mpc

**Comment by coachbindel** [comment]
That worked! Thank you.

**Comment by jcrossbdn** [comment]
Fantastic!
