### ISSUE TITLE
Lots of "issues" with streams

### ISSUE THREAD

**Issue by majkrebs** [jcrossbdn/fpp-after-hours#25]
![Screenshot 2024-02-19 224531](https://github.com/jcrossbdn/fpp-after-hours/assets/10644549/e86f6a8d-383a-44ac-8906-867135a634dd)

Is there something wrong with my setup or or does the plugin hate my choices for playing streams? 

BTW, the first one is actually playing in spite of the exclamation mark.

I should have provided some more info:

FPP Version: | 8.x-master-174-gd1ec8350
Platform: | Raspberry Pi (Pi 3 Model B)
FPP OS Build: | v2024-02
OS Version: | Raspbian GNU/Linux 12 (bookworm)
Local Git Version: | d1ec835

With latest version from github.

**Comment by majkrebs** [comment]
So after I said that, I tried to change the volume and now the plugin won't stay started. Lost all my stations as well so I rebooted. Yep all the stations are now kaput. I did click check for updates in between - told me there were none. Maybe that kaputted my streams?

**Comment by jcrossbdn** [comment]
I just pushed an update that will hopefully sort out the improper stream failure notices.  All your streams look good to me (after this update)

**Comment by jcrossbdn** [comment]
> So after I said that, I tried to change the volume and now the plugin won't stay started. Lost all my stations as well so I rebooted. Yep all the stations are now kaput. I did click check for updates in between - told me there were none. Maybe that kaputted my streams?

It is possible that a character broke the configuration file.  There is a history file of every change made to the config in /home/fpp/media/plugindata/fpp-after-hours-config.history if you could share the last few lines that show all the loaded streams and then no loaded streams

**Comment by jcrossbdn** [comment]
I have pushed another update that does a bit more error handling specifically on volumes.  I'm also noticing that plugin updates may not be working on the latest v8 (d1ec835) as I am not getting the update after pushing the change.  I had to delete the fpp-after-hours directory in plugins (you can also uninstall from the plugin manager but that takes a bit of time to remove mpd and mpc).

You should be able to uninstall or delete the fpp-after-hours plugin directory and not lose your configuration files as configurations are stored in the plugindata directory so that updates can work.

**Comment by majkrebs** [comment]
2024-02-19 22:43:02 - {"activeSource":"internet","streams":{"1000 Christmas hits":{"active":"false","url":"https:\/\/1000christmashits.stream.laut.fm","volume":"70","priority":4,"uid":4},"Christimas Hits 1":{"active":"false","url":"http:\/\/94.23.57.5:9099","volume":"70","priority":3,"uid":3},"Mormon Choir":{"active":"false","url":"http:\/\/192.96.205.59:7000","volume":"91","priority":5,"uid":5},"North pole radio":{"active":"false","url":"http:\/\/85.25.217.22:8050","volume":"80","priority":2,"uid":1},"Radio xmas":{"active":"true","url":"http:\/\/77.75.16.229:443","volume":"100","priority":1,"uid":2}}}
2024-02-19 22:43:02 - {"activeSource":"internet","streams":{"1000 Christmas hits":{"active":"false","url":"https:\/\/1000christmashits.stream.laut.fm","volume":"70","priority":4,"uid":4},"Christimas Hits 1":{"active":"false","url":"http:\/\/94.23.57.5:9099","volume":"70","priority":3,"uid":3},"Mormon Choir":{"active":"false","url":"http:\/\/192.96.205.59:7000","volume":"90","priority":5,"uid":5},"North pole radio":{"active":"false","url":"http:\/\/85.25.217.22:8050","volume":"80","priority":2,"uid":1},"Radio xmas":{"active":"true","url":"http:\/\/77.75.16.229:443","volume":"100","priority":1,"uid":2}}}
2024-02-19 22:43:02 - {"activeSource":"internet","streams":{"1000 Christmas hits":{"active":"false","url":"https:\/\/1000christmashits.stream.laut.fm","volume":"70","priority":4,"uid":4},"Christimas Hits 1":{"active":"false","url":"http:\/\/94.23.57.5:9099","volume":"70","priority":3,"uid":3},"Mormon Choir":{"active":"false","url":"http:\/\/192.96.205.59:7000","volume":"89","priority":5,"uid":5},"North pole radio":{"active":"false","url":"http:\/\/85.25.217.22:8050","volume":"80","priority":2,"uid":1},"Radio xmas":{"active":"true","url":"http:\/\/77.75.16.229:443","volume":"100","priority":1,"uid":2}}}
2024-02-19 22:43:02 - {"streams":null,"activeSource":"internet"}
2024-02-19 22:43:02 - {"streams":null,"activeSource":"internet"}

A few entries when the entries were there and then not. I only added one entry last night and it played all night.

**Comment by majkrebs** [comment]
I clicked the update button and it said one was available and hit update now. Stop and started a stream without issue. 

Added North Pole Radio and got the exclamation again. I am listening to it on my PC so it is up. Also ran a tracert to it from FPP so the server is up:

14  atlantic2689.serverprofi24.de (85.25.217.22)  111.171 ms !X  111.371 ms !X  111.315 ms !X

Added 1000 Christmas hits https://1000christmashits.stream.laut.fm and it is also exclaimed!

Also rebooted and issue persists. I really only need one but my favorite was North Pole Radio and it doesn't work. Also I added a Halloween station last year and would like the ability to move from one stream to another with a click.

**Comment by majkrebs** [comment]
I don't think I actually got the updates by clicking the button. I did an uninstall and then installed. My configured stations are there and showing okay status now. It looks like North Pole Radio is good! But so are the others.

Thanks for your work on this plugin. You make the whole day more enjoyable when I can hear the music.

**Comment by jcrossbdn** [comment]
Thanks so much!

This update had a lot of changes to make it work on fpp8 as well as modernize the user interface so I'm happy to have people testing and reporting issues now rather than at the busy time of Halloween/Christmas ;)

I am concerned about the stream section of the config getting deleted.  I don't see a reason from the history why that would have happened.  Would you be able to check your apache2-error.log for any errors around 2024-02-19 22:43:02?  I have tried everything I can but have not been able to reproduce this which is very concerning.  I see the volume change taking place but that should not have deleted your streams.  I may have to go the other way I was thinking using a sqlite database to store stream information instead of using json especially with the ability to change settings so rapidly, or build a service specifically for the config write.

I have also opened a ticket for the plugin not updating in fpp at [https://github.com/FalconChristmas/fpp/issues/1812](https://github.com/FalconChristmas/fpp/issues/1812).  I am assuming that this issue is impacting all plugins, but I can't be sure because I only have one published to the repository.

**Comment by majkrebs** [comment]
Nothing in particular at 22:43 so I copied in a few extra lines so you can see context. For more context, this server was recently imaged as one of the updates blew up the index/status page so I downloaded a new image onto the SDCard. This happened in the middle of trying to get After Hours to work but was directly related to doing an FPP update. It looks like I did that Sunday night as all the "errors" in the log file before these messages were about saving settings. Interesting thing about the logs is that date/time changes along the way. And you can see I had loaded the projector plugin along the way as well.

[Sun Feb 18 22:50:19.402001 2024] [proxy_fcgi:error] [pid 4759:tid 1649398720] [client 192.168.10.109:54421] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Sun Feb 18 22:51:08.365244 2024] [proxy_fcgi:error] [pid 4813:tid 1649279936] [client 192.168.10.109:54434] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Sun Feb 18 22:51:50.069574 2024] [proxy_fcgi:error] [pid 4813:tid 1640887232] [client 192.168.10.109:54440] AH01067: Failed to read FastCGI header, referer: http://fpp01/index.php

[Sun Feb 18 22:51:50.069790 2024] [proxy_fcgi:error] [pid 4813:tid 1640887232] (104)Connection reset by peer: [client 192.168.10.109:54440] AH01075: Error dispatching request to : , referer: http://fpp01/index.php

[Wed Oct 11 05:53:00.777877 2023] [proxy:error] [pid 1211:tid 1725072320] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:00.796135 2023] [proxy_fcgi:error] [pid 1211:tid 1725072320] [client 192.168.10.109:54445] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01/index.php

[Wed Oct 11 05:53:00.992092 2023] [proxy:error] [pid 1212:tid 1725072320] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:00.992336 2023] [proxy_fcgi:error] [pid 1212:tid 1725072320] [client 192.168.10.109:54446] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01/index.php

[Sun Feb 18 22:56:56.173077 2024] [proxy_fcgi:error] [pid 1212:tid 1647440832] [client 192.168.10.109:54478] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Mon Feb 19 22:18:34.367086 2024] [proxy_fcgi:error] [pid 1212:tid 1683108800] [client 192.168.10.109:55655] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "DEVICE" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 9; PHP message: PHP Warning:  Undefined array key "BAUD_RATE" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 10; PHP message: PHP Warning:  Undefined array key "CHAR_BITS" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 11; PHP message: PHP Warning:  Undefined array key "STOP_BITS" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 12; PHP message: PHP Warning:  Undefined array key "PARITY" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 13; PHP message: PHP Warning:  Undefined array key "IP" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 15; PHP message: PHP Warning:  Undefined array key "PORT" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 16; PHP message: PHP Warning:  Undefined array key "ENABLED" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 17; PHP message: PHP Warning:  Undefined array key "PROJECTOR" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 18; PHP message: PHP Warning:  Undefined array key "PROJ_PASSWORD" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 19; PHP message: PHP Warning:  Undefined array key "PROJ_PROTOCOL" in /home/fpp/media/plugins/FPP-Plugin-Projector-Control/functions.inc.php on line 20', referer: http://fpp01.local/index.php

[Mon Feb 19 22:41:43.029387 2024] [proxy_fcgi:error] [pid 1212:tid 1716679616] [client 192.168.10.109:55821] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Mon Feb 19 22:55:20.496530 2024] [proxy:error] [pid 1211:tid 1518318528] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Mon Feb 19 22:55:20.497052 2024] [proxy_fcgi:error] [pid 1211:tid 1518318528] [client 192.168.10.109:55974] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/index.php

[Wed Oct 11 05:53:01.350590 2023] [proxy:error] [pid 1236:tid 1725006784] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:01.350462 2023] [proxy:error] [pid 1237:tid 1526657984] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:01.360355 2023] [proxy_fcgi:error] [pid 1236:tid 1725006784] [client 192.168.10.109:56965] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Wed Oct 11 05:53:01.360393 2023] [proxy_fcgi:error] [pid 1237:tid 1526657984] [client 192.168.10.109:56967] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Wed Oct 11 05:53:01.527822 2023] [proxy:error] [pid 1237:tid 1716614080] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:01.527934 2023] [proxy_fcgi:error] [pid 1237:tid 1716614080] [client 192.168.10.109:56964] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Wed Oct 11 05:53:01.543294 2023] [proxy:error] [pid 1236:tid 1716614080] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:01.543400 2023] [proxy_fcgi:error] [pid 1236:tid 1716614080] [client 192.168.10.109:56969] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Wed Oct 11 05:53:01.544755 2023] [proxy:error] [pid 1237:tid 1699828672] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php8.2-fpm.sock (localhost:8000) failed

[Wed Oct 11 05:53:01.544860 2023] [proxy_fcgi:error] [pid 1237:tid 1699828672] [client 192.168.10.109:56968] AH01079: failed to make connection to backend: httpd-UDS, referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Tue Feb 20 21:56:01.795164 2024] [proxy_fcgi:error] [pid 1237:tid 1577014208] [client 192.168.10.109:57025] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

[Tue Feb 20 21:56:06.446296 2024] [proxy_fcgi:error] [pid 1236:tid 1560236992] [client 192.168.10.109:57043] AH01071: Got error 'PHP message: fpp-after-hours... ERROR: No reachable streams could be started', referer: http://fpp01.local/plugin.php?_menu=content&plugin=fpp-after-hours&page=fpp-after-hours.php

**Comment by jcrossbdn** [comment]
Yeah there was a lot going on there.  I'm hoping it was just a fluke but please let me know if the config gets wiped out again.  If I hear one more instance of that I will update the plugin to use a database instead of json for configuration data.
