### ISSUE TITLE
FPP 8 compatability

### ISSUE THREAD

**Issue by andyaz** [jcrossbdn/fpp-after-hours#27]
Any anticipated timeline to make this plugin compatible with FPP 8?

**Comment by jcrossbdn** [comment]
That was done a few months ago. What are you experiencing?JasonSent from my iPhoneOn Sep 13, 2024, at 11:30 PM, andyaz ***@***.***> wrote:﻿
Any anticipated timeline to make this plugin compatible with FPP 8?

**Comment by andyaz** [comment]
Ok, I tried it again and this time it all works. Last time I tried I believe there was an issue with the dependencies versions for the new OS. Anyway, I installed the plugin again, manually installed the dependencies in SSH so I could see what they were doing and all went successfully. Loaded my stations and works like a champ.  

All that is left is to get it moved from the untested plugins list to the working plugins list in FPP...
![fpp8 afterhours music not tested with this version](https://github.com/user-attachments/assets/4e5c5d3e-8b14-4def-b03a-7a926ecca35c)

**Comment by jcrossbdn** [comment]
Fantastic.  I have just seen a post on falconchristmas of someone else also having this issue so I'm hoping to get some more detailed information when it is failing so we can figure this out and get it solved.

Also thanks for pointing out that the plugin was showing up in the not tested list.  I looked at one of Chris's plugins and found my issue in my pluginInfo.sjon fil.  I thought I could just say the minimum fpp version was 7.0 and it would work on 8 and 9 in the future and so on, however, it appears that we have to specify major versions independently even if they use the same branch... lesson learned.

Thanks again!

Jason

**Comment by jcrossbdn** [comment]
close

**Comment by jcrossbdn** [comment]
I'm actually thinking that the solution may be to change the install command to do an apt update and apt upgrade before the install... hate to do that on a plugin's installer though due to the time it can take to perform that task.
