### ISSUE TITLE
After hours plugin will not work on latest 7.5 FPP. 

### ISSUE THREAD

**Issue by meckman** [jcrossbdn/fpp-after-hours#29]
I updated this plugin and it keeps giving me the following:

! ! ! Additional Software Must Be Installed ! ! !

will run sudo apt update && sudo apt -y install mpd mpc

i update, reboot, and it comes back with the same message. 

This is what happens when I click the Install button: 
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
Building dependency tree...
Reading state information...
147 packages can be upgraded. Run 'apt list --upgradable' to see them.

fpp-after-hours additional software installation complete

running on a Raspberry Pi. Worked great for years. Not sure what I’m doing wrong or if there is an issue with the code.

**Comment by meckman** [comment]
I did see the comment about going to the SSH Shell and I did log in and enter the "sudo apt update && sudo apt -y install mpd mpc" command.  I received this back.  Looks like it's having an issue with the host name.  Not sure how to resolve.  It's been this name for 4-5 years.

fpp@FPP-Projector:~ $ sudo apt update && sudo apt -y install mpd mpc
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                                                        
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done                                                                                                                                                             
Reading state information... Done                                                                                                                                                            
147 packages can be upgraded. Run 'apt list --upgradable' to see them.                                                                                                                       
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                                                        
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by jcrossbdn** [comment]
Hi Michael,It appears that you have a DNS issue on your system (which is quite common). But if does appear that the repos are resolving so it’s only an issue with the local host dns entry, which should not be a game stopper for this install.if you want to try running:sudo dpkg --configure -aand then the apt install command again that may be enough to get this installed properly.JasonSent from my iPhoneOn Nov 23, 2024, at 4:48 AM, Michael Eckman ***@***.***> wrote:﻿
I did see the comment about going to the SSH Shell and I did log in and enter the "sudo apt update && sudo apt -y install mpd mpc" command.  I received this back.  Looks like it's having an issue with the host name.  Not sure how to resolve.  It's been this name for 4-5 years.
***@***.***:~ $ sudo apt update && sudo apt -y install mpd mpc
sudo: unable to resolve host FPP-Projector: Name or service not known
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
147 packages can be upgraded. Run 'apt list --upgradable' to see them.
sudo: unable to resolve host FPP-Projector: Name or service not known
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by meckman** [comment]
I get this error with the suggested command. As for DNS I’m able to update FPP via github within ***@***.***:~ $ sudo dpkg --cofigure -a sudo: unable to resolve host FPP-Projector: Name or service not known dpkg: error: unknown option --cofigure Type dpkg --help for help about installing and deinstalling packages [*]; Use 'apt' or 'aptitude' for user-friendly package management; Type dpkg -Dhelp for a list of dpkg debug flag values; Type dpkg --force-help for a list of forcing options; Type dpkg-deb --help for help about manipulating *.deb files;  Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
    On Saturday, November 23, 2024 at 11:06:58 AM EST, Jason Cross ***@***.***> wrote:  
 
 

Hi Michael,It appears that you have a DNS issue on your system (which is quite common). But if does appear that the repos are resolving so it’s only an issue with the local host dns entry, which should not be a game stopper for this install.if you want to try running:sudo dpkg --configure -aand then the apt install command again that may be enough to get this installed properly.JasonSent from my iPhoneOn Nov 23, 2024, at 4:48 AM, Michael Eckman ***@***.***> wrote:﻿
I did see the comment about going to the SSH Shell and I did log in and enter the "sudo apt update && sudo apt -y install mpd mpc" command. I received this back. Looks like it's having an issue with the host name. Not sure how to resolve. It's been this name for 4-5 years.
***@***.***:~ $ sudo apt update && sudo apt -y install mpd mpc
sudo: unable to resolve host FPP-Projector: Name or service not known
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
147 packages can be upgraded. Run 'apt list --upgradable' to see them.
sudo: unable to resolve host FPP-Projector: Name or service not known
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by jcrossbdn** [comment]
You have a typo in “configure”. :)JasonSent from my iPhoneOn Nov 23, 2024, at 11:49 AM, Michael Eckman ***@***.***> wrote:﻿
 I get this error with the suggested command. As for DNS I’m able to update FPP via github within ***@***.***:~ $ sudo dpkg --cofigure -a sudo: unable to resolve host FPP-Projector: Name or service not known dpkg: error: unknown option --cofigure Type dpkg --help for help about installing and deinstalling packages [*]; Use 'apt' or 'aptitude' for user-friendly package management; Type dpkg -Dhelp for a list of dpkg debug flag values; Type dpkg --force-help for a list of forcing options; Type dpkg-deb --help for help about manipulating *.deb files;  Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !

    On Saturday, November 23, 2024 at 11:06:58 AM EST, Jason Cross ***@***.***> wrote:  

 

 



Hi Michael,It appears that you have a DNS issue on your system (which is quite common). But if does appear that the repos are resolving so it’s only an issue with the local host dns entry, which should not be a game stopper for this install.if you want to try running:sudo dpkg --configure -aand then the apt install command again that may be enough to get this installed properly.JasonSent from my iPhoneOn Nov 23, 2024, at 4:48 AM, Michael Eckman ***@***.***> wrote:﻿

I did see the comment about going to the SSH Shell and I did log in and enter the "sudo apt update && sudo apt -y install mpd mpc" command. I received this back. Looks like it's having an issue with the host name. Not sure how to resolve. It's been this name for 4-5 years.

***@***.***:~ $ sudo apt update && sudo apt -y install mpd mpc

sudo: unable to resolve host FPP-Projector: Name or service not known

Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease

Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

147 packages can be upgraded. Run 'apt list --upgradable' to see them.

sudo: unable to resolve host FPP-Projector: Name or service not known

E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by meckman** [comment]
After I correctly type it I get this:
![IMG_1934](https://github.com/user-attachments/assets/8ecba997-c074-41f7-a719-8e2b6ba57667)

I’m not at home and I’m VPN-ing back to my network via my NAS. I’m doing this all on my phone and not sure I can a actually select anything.   Probably have to wait til I get back home.

**Comment by jcrossbdn** [comment]
Install the package maintainers version.The plug-in will reconfigure it when it starts up next time.JasonSent from my iPhoneOn Nov 23, 2024, at 2:02 PM, Michael Eckman ***@***.***> wrote:﻿
After I correctly type it I get this:
IMG_1934.jpeg (view on web)
I’m not at home and I’m VPN-ing back to my network via my NAS. I’m doing this all on my phone and not sure I can a actually select anything.   Probably have to wait til I get back home.

**Comment by meckman** [comment]
I finally was able to get home and this did resolve my issue. Thanks for the help.
