### ISSUE TITLE
Crashes on run start script

### ISSUE THREAD

**Issue by kd7hgt** [jcrossbdn/fpp-after-hours#3]
Trying to test it before I add it to the playlist.  When I hit run I get this error.
Yes I do have a usb sound device that I use to play my normal show. 
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours-class.php:277 Stack trace: #0 /home/fpp/media/scripts/fpp-after-hours-start.php(8): fppAfterHours->getFPPActiveSoundCardName() #1 /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours.php(16): include('/home/fpp/media...') #2 /opt/fpp/www/plugin.php(92): include_once('/home/fpp/media...') #3 {main} thrown in /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours-class.php on line 277
![2018-12-31](https://user-images.githubusercontent.com/38399484/50564364-432aad00-0cf2-11e9-99c3-8be51dd2f0a3.png)

**Comment by jcrossbdn** [comment]
Can you click the advanced tab then "Plugin Github Status   Click here to update"

Then please provide the data displayed in the advanced tab under "All Sound Cards" and "Settings"

**Comment by kd7hgt** [comment]
When I go to advanced I get another fatal error also



Sent from my Sprint Samsung Galaxy S8+.


-------- Original message --------

**Comment by jcrossbdn** [comment]
Can you please do the following as I am unable to reproduce this:

Click Help --- SSH Shell
login: fpp
password: falcon

type in: sudo aplay -l | grep '^card' | sed -e 's/^card //' -e 's/:[^\[]*\[/:/' -e 's/\].*\[.*\].*//' | uniq

please send the response from that command.
Are you using a Pi or BBB?

**Comment by kd7hgt** [comment]
I am using a BBB[cid:image003.png@01D4A1C5.76B91FA0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jcrossbdn** [comment]
The above image did not link properly so I cannot see it.  Can you please do the following as I am unable to reproduce this:

Click Help --- SSH Shell
login: fpp
password: falcon

type in: **sudo aplay -l**
(l is a lower case L)

please send the response from that command (even copy/paste all the output)

**Comment by kd7hgt** [comment]
[cid:image003.png@01D4A1E0.6CBAE180]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jcrossbdn** [comment]
The image is still not visible to me on github.  Can you please email it to info@crosslights.ca

**Comment by jcrossbdn** [comment]
I updated the getSystemSoundCards function to use regex instead of grep and expect that has corrected the issue with BBBs running that image.

Closing this ticket as I have not heard back from the complainant since receiving confirmation that the fatal error no longer appears since making this update.
