### ISSUE TITLE
BBB FPP 8.3.1 Can't Add Stream

### ISSUE THREAD

**Issue by nmiller0113** [jcrossbdn/fpp-after-hours#30]
I have a fresh install of FPP 8.3.1 and added the After Hours Music Plugin. The plugin install completed successfully as well as the additional install items following the plugin install.

Following the completed install, when I click on +Add Stream, nothing happens. I tried on both Chrome and Safari.  I even restarted FPP. No luck. Not sure what else to do, this worked on the previous 7.x install I had running before I ran this brand new install (not upgrade). Thanks!

**Comment by jcrossbdn** [comment]
Merged with issue 31 because nmiller0113 had also commented on 31 so should also get the notifications.
