### ISSUE TITLE
Stop script not working in playlist

### ISSUE THREAD

**Issue by jcrossbdn** [jcrossbdn/fpp-after-hours#32]
reported on facebook "FPP, Falcon Player".

Start script would work but stop script would not from playlist.

I believe the issue is the execute bit is not being set when the scripts are migrated to the fpp scripts directory.

**Comment by jcrossbdn** [comment]
A fix has been pushed to set the execute bit on the start and stop script files.

**Comment by meckman** [comment]
I brought in the updates yesterday and unfortunately the stop script did not work this morning. I still had to manually stop the after hours plug in.

**Comment by jcrossbdn** [comment]
can you provide the screenshot from the "ls" command I asked you to run?

**Comment by meckman** [comment]
![IMG_1993](https://github.com/user-attachments/assets/33ea6063-de1b-4679-8736-c8ebb39634a1)

**Comment by jcrossbdn** [comment]
Everything looks fine there.  Can you check the fpp logs to make sure that that playlist is actually running properly.  If it is then perhaps fpp logs will show something else at the lead out time.

**Comment by meckman** [comment]
This is the only thing I noticed in the log.  Something about Section position 0 is outside of section New

2024-12-10 00:00:10.745 (29739) [Plugin] src/FPPMonitorPlugin.cpp:1151: FPPMon - Retrieved Authentication Token from https://kulplights.com
2024-12-10 00:03:11.434 (1878) [Plugin] src/FPPMonitorPlugin.cpp:1151: FPPMon - Retrieved Authentication Token from https://kulplights.com
2024-12-10 07:44:57.026 (1878) [Playlist] /opt/fpp/src/playlist/Playlist.cpp:743: Section position 0 is outside of section New

**Comment by jcrossbdn** [comment]
Hmm, I'm at a loss at this point.  I can't see anything obviously wrong with fah.

What version of fpp are you currently running?

Do you receive any errors or warnings if you run the following three commands (one at a time) from the command line:
php /home/fpp/media/scripts/fpp-after-hours-stop.php

php /home/fpp/media/scripts/fpp-after-hours-start.php

php /home/fpp/media/scripts/fpp-after-hours-stop.php


I'd be happy to schedule a zoom call to delve into this specific case a little more if there is no obvious error from the above.
I am central standard time so we would have to coordinate a time that works for both of us.  I can setup a meeting once I know the times that work for you.

**Comment by napdsp** [comment]
I have a similar problem. When I run
php /home/fpp/media/scripts/fpp-after-hours-start.php
I get
PHP Notice:  Undefined variable: runFromCronMonitorStream in /home/fpp/media/scripts/fpp-after-hours-start.php on line 7
9

**Comment by meckman** [comment]
I ran the commands I got the following messages:
fpp@FPP-Projector:~ $ php /home/fpp/media/scripts/fpp-after-hours-stop.php
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
fpp@FPP-Projector:~ $ php /home/fpp/media/scripts/fpp-after-hours-start.php
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
fpp@FPP-Projector:~ $ php /home/fpp/media/scripts/fpp-after-hours-stop.php
sudo: unable to resolve host FPP-Projector: Name or service not known                                                                                
fpp@FPP-Projector:~ $

I did notice that the after hours service ran with the start command and then shut off after the stop command.  So the scripts are working.

FPP Version: | 7.5-7-gfefac7b7
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2023-12
OS Version: | Raspbian GNU/Linux 11 (bullseye)
Hardware Serial Number: | 1000000010cb9e85
Kernel Version: | 6.1.21-v7l+

I'm available anytime today for a zoom up til 3pm eastern.  I can also be available from 4:00-5:15 eastern

**Comment by jcrossbdn** [comment]
I have found a few minor things in the start and stop scripts that I have modified.  Please update the plugin to current and see if the issue persists.

**Comment by meckman** [comment]
I downloaded the updates yesterday and the plugin was still running this morning.

**Comment by jcrossbdn** [comment]
if you add a new test playlist with just the fpp stop command and run it from the status screen what happens?

**Comment by meckman** [comment]
I added the Fpp After Hours - Stop in the scheduler as a command to fire at sunrise. I hit the “run now” button and it stopped the plugin from playing.  It’s not exactly what the fix we were going for but if it works then that’s fine with me.

**Comment by jcrossbdn** [comment]
I was more curious as to whether it would stop not from the script section but from the playlist section.  I created a test playlist with every variant of start and stop on my side to make sure all the scripts were functioning.
![image](https://github.com/user-attachments/assets/1dc5aa77-6201-4aa0-8e0d-6e4263863aeb)

**Comment by meckman** [comment]
I created the attached playlist and it started and stopped the plug-in as it should each time.  I even added that playlist to the schedule and again it started and stopped as it should.
![Screenshot 2024-12-12 142147](https://github.com/user-attachments/assets/0e608eb9-4c16-4f89-87ad-620acbb841d3)

**Comment by jcrossbdn** [comment]
Perhaps try changing the failing playlist to use FPP Commands instead of the Script option.

Playlist / Add a Sequence/Entry
![image](https://github.com/user-attachments/assets/f92d86f4-eecf-4e7f-9643-e7fc031ce9e7)

**Comment by meckman** [comment]
I just created a new playlist that looks exactly like the old one and it's working just fine.  Not sure what is wrong with the old playlist that it skips over the stop script.  This issue appears to be resolved.  This can be closed.  Thanks for all the help on this odd ball issue.

**Comment by jcrossbdn** [comment]
Yeah this one was making me scratch my head.  I was leaning heavily towards an issue with the playlist or the fpp install, however I did find a few things related to fading in the scripts that was not quite right so at least this got those fixed :)

Glad you are up and running now.
