### ISSUE TITLE
Streams won't start

### ISSUE THREAD

**Issue by Bsnyder97** [jcrossbdn/fpp-after-hours#33]
When pressing play, the button will gray out for a couple of seconds then return with nothing playing. No error messages are shown. 

FPP is V8.4.1 running on a raspi 3B.

Trying links like:

https://radio.themillerlights.com:8000/radio.mp3
http://s4.myradiostream.com:8238
http://51.255.235.165:5192
https://kathy.torontocast.com:2960

This is my first attempt at running fpp-after-hours, so there is a chance I a doing something wrong, but I don't think so. The links above will play if I paste them into a browser.

**Comment by jcrossbdn** [comment]
please make sure that your pi can access the internet and that dns is properly configured

**Comment by Bsnyder97** [comment]
They should be able to access the internet as they sucessfully updated from FPP 8.4 to 8.4.1.

So I imaged brand new micro SD cards with 8.4 and now fpp-after-hours works perfectly. Something must be wrong with my old memory cards?

At any rate it is working now. Thank you.
