### ISSUE TITLE
List not showing in 7.5.x

### ISSUE THREAD

**Issue by bcarriveau** [jcrossbdn/fpp-after-hours#34]
![Screenshot_20241227_054434_Chrome](https://github.com/user-attachments/assets/56a78a56-280f-40f9-965a-8f9847ee3a4c)

But shows in old ui

![Screenshot_20241227_054514_Chrome](https://github.com/user-attachments/assets/4b01087a-269e-4f64-b10a-aded29b29e80)

**Comment by jcrossbdn** [comment]
Can you change one of the priority 9 entries to priority 8 and see if that solves it?  I can't imagine that would cause an issue, however, I would like to rule it out.

**Comment by bcarriveau** [comment]
> Can you change one of the priority 9 entries to priority 8 and see if that solves it? I can't imagine that would cause an issue, however, I would like to rule it out.

Good eyes lol. I will in a few hrs! Thanks for the plug in regardless!

**Comment by bcarriveau** [comment]
That unfortantly did not fix it.

**Comment by bcarriveau** [comment]
had to have been a bad or corrupt backup file in the plugindata folder. blew everything away and reinstalled and it works again.
