### ISSUE TITLE
what caused a fatal error

### ISSUE THREAD

**Issue by Fire84** [jcrossbdn/fpp-after-hours#4]
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours-class.php:277 Stack trace: #0 /home/fpp/media/scripts/fpp-after-hours-start.php(8): fppAfterHours->getFPPActiveSoundCardName() #1 /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours.php(16): include('/home/fpp/media...') #2 /opt/fpp/www/plugin.php(92): include_once('/home/fpp/media...') #3 {main} thrown in /home/fpp/media/plugins/fpp-after-hours/fpp-after-hours-class.php on line 277

**Comment by jcrossbdn** [comment]
That should have been fixed in an earlier release.. Can you please do the following to update to the current release:

from fpp click Help, SSH Shell
fpp login: fpp
password: falcon
type: sudo /opt/fpp/scripts/update_plugin fpp-after-hours

that should update the plugin. I have made a change just now so that the page won't die on the advanced tab so at least people can update if we are still chasing a bug.

**Comment by Fire84** [comment]
keeps saying no such file or directory

**Comment by Fire84** [comment]
ok got it to update.  On the internet radio tab I put in a link and the box says reachable but when I click run start script I briefly get the now playing to say something but it shuts off to fast to read what it says and then nothing happens.  ??????

**Comment by jcrossbdn** [comment]
okay good, can you reply with the link to the stream you are trying to run?
and are you running a BB or Pie?

**Comment by Fire84** [comment]
http://us4.internet-radio.com:8258/;stream
https://www.internet-radio.com/station/0099ryan1/
http://www.christmasradiolive.com/

I tried these 3 and a few others all with the same result, also I'm using a pi 3B+

**Comment by jcrossbdn** [comment]
Okay this is the most common issue I get questions about.
The first one should be: http://167.114.64.181:8232
The second one should be: http://us4.internet-radio.com:8258
The third one doesn't seem to want to work

I am trying to figure out how to improve the plugin to automatically determine (and possibly correct) the correct URL to use.

I have a section in the help file on how to find the proper URL but the whole process is rather clumsy right now (https://github.com/jcrossbdn/fpp-after-hours#finding-the-url-of-your-favorite-internet-radio-station)

I also added a reference to the help page from the fpp "Press F1 for help" page just now (plugin needs to be updated through the advanced tab to get this).

**Comment by Fire84** [comment]
YEP That fixed it, works great Jason!!! Thanks....you da man!!!! now i just need to find a good country music channel....lol
