### ISSUE TITLE
Does not install on FPP 3.0

### ISSUE THREAD

**Issue by dkulp** [jcrossbdn/fpp-after-hours#5]
The pluginInfo.json file needs to have the max set higher.   It won't install on FPP 3.0.

**Comment by jcrossbdn** [comment]
Darn I did not get a notification about your message.  I have yet to upgrade to FPP 3 so hopefully updating this value won't install a broken version of the plugin

**Comment by jcrossbdn** [comment]
I have updated branches and modified the pluginInfo.json file to work with 3.x
There appears to be an mpd issue in the new OS returning an error (and giving me loud static with the playing music).  I am trying to isolate and correct this issue... Changing mpd ports did not correct the problem.

**Comment by tjbaker6** [comment]
any progress?
 
Its a cool plugin bur right now it aborts when trying to play

**Comment by jcrossbdn** [comment]
@tjbaker6 
What is your configuration? USB sound card? (if so what type).
Are you comfortable at the command line if I come up with a few test commands to run to see if your issue is the same as what I'm seeing on mine?

For the life of me I cannot figure out why mpd is not working properly.  It may be that the software has not caught up with the os but I've yet to find a solution (or even identify the actual problem for that matter).  I was looking at other options that would play internet streams with the ability to control it from the plugin but I settled on mpd last year because it had the most options.

> any progress?
> 
> Its a cool plugin bur right now it aborts when trying to play

**Comment by jcrossbdn** [comment]
@tjbaker6 
I have pushed a few new updates to github which seem to have corrected the issues that I was having (basically adding a few new parameters to the mpd config file and changing how volumes were set).

Can you please do a plugin update in fpp (Content Setup/Plugin Manager, "Check for Updates checkbox" beside After Hours Music Player Plugin, and then upgrade plugin).

I'm hoping that this new current version will work for you.  I haven't tried it on my other pi yet but will try that tomorrow night.

**Comment by tjbaker6** [comment]
@jcrossbdn   Yep its a generic USB (https://www.amazon.com/Syba-external-Adapter-Windows-C-Media/dp/B001MSS6CS) identifies as a c media usb in FPP.   Happy to try some things for you

**Comment by jcrossbdn** [comment]
> @jcrossbdn Yep its a generic USB (https://www.amazon.com/Syba-external-Adapter-Windows-C-Media/dp/B001MSS6CS) identifies as a c media usb in FPP. Happy to try some things for you

Please try updating the plugin and let me know if it is still not working for you.

**Comment by tjbaker6** [comment]
@jcrossbdn  -- no luck Jason.  I updated the plugin.  it appears to try to start to play, but before the counter moves off 00:00:00 it goes back to stopped state.

**Comment by jcrossbdn** [comment]
@tjbaker6
Okay, can you provide me with the stream URL you are trying to use?

Thanks!

Jason

**Comment by dkulp** [comment]
Seems to be another bug....  It's calling "mpc output" to get the outputs, but that's not the right command.  It's "mpc outputs"  Once I fixed that, I was able to get it to play.

**Comment by jcrossbdn** [comment]
> Seems to be another bug.... It's calling "mpc output" to get the outputs, but that's not the right command. It's "mpc outputs" Once I fixed that, I was able to get it to play.

Thank you! I have made this update and pushed to master branch.

Interestingly enough both "mpc output" and "mpc outputs" seem to be accepted by mpc on my pi:
```
root@FPP:/home/fpp# mpc output
Output 1 (bcm2835 ALSA) is disabled
Output 2 (USB Audio Device) is enabled
root@FPP:/home/fpp# mpc outputs
Output 1 (bcm2835 ALSA) is disabled
Output 2 (USB Audio Device) is enabled
root@FPP:/home/fpp#
```

But since you are correct and have said that it fixed the issues you were having I am happy to push this update!

**Comment by dkulp** [comment]
Interesting.  On the 3.5 Beaglebone images:

```
fpp@FPPMaster:~/media/plugins/fpp-after-hours$ mpc outputs
Output 1 (HiFi-FMT / VAST ELECTRONICS) is enabled
	allowed_formats=""
	dop="0"
fpp@FPPMaster:~/media/plugins/fpp-after-hours$ mpc output
unknown command "output"
Usage: mpc [options] <command> [<arguments>]
mpc version: 0.31
See man 1 mpc or use 'mpc help' for more help.
fpp@FPPMaster:~/media/plugins/fpp-after-hours$
```

**Comment by jcrossbdn** [comment]
`

> Interesting. On the 3.5 Beaglebone images:
> 
> ```
> fpp@FPPMaster:~/media/plugins/fpp-after-hours$ mpc outputs
> Output 1 (HiFi-FMT / VAST ELECTRONICS) is enabled
> 	allowed_formats=""
> 	dop="0"
> fpp@FPPMaster:~/media/plugins/fpp-after-hours$ mpc output
> unknown command "output"
> Usage: mpc [options] <command> [<arguments>]
> mpc version: 0.31
> See man 1 mpc or use 'mpc help' for more help.
> fpp@FPPMaster:~/media/plugins/fpp-after-hours$
> ```

Wow it is interesting how libraries are different between distributions!
