### ISSUE TITLE
Keeps bringing me to Install Screen

### ISSUE THREAD

**Issue by Spankyty** [jcrossbdn/fpp-after-hours#7]
FPP Version: v3.5.4

I installed the required additional software. I rebooted. Now I cannot get that screen back to set things up. It brings me to this screen again...

![image](https://user-images.githubusercontent.com/17915767/69893290-4e5cd300-12dd-11ea-85bc-533e52ab7c53.png)

**Comment by jcrossbdn** [comment]
@Spankyty interesting...

Can you drop to command line (Help -> SSH Shell, fpp, falcon, and type in "mpc version" and let me know what it says...

If it says "command not found" can you enter the below command (hitting enter afterwards):
sudo apt-get -y update && sudo apt-get -y install mpd mpc

and let me know the output from that.  Please ensure that your Pi is able to get to the internet when running this command.

if everything has responded positively can you then type in "systemctl status mpd" and hit enter and send the results from that command.

you can then type "exit" and close the command window.

Jason

**Comment by Spankyty** [comment]
**First step-**
mpd error: Network is unreachable

**I continued anyway and ran step 2-**
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Reading package lists... Done                                                                                                                                                                                      
Building dependency tree                                                                                                                                                                                           
Reading state information... Done                                                                                                                                                                                  
mpc is already the newest version (0.31-1).                                                                                                                                                                        
mpd is already the newest version (0.21.5-3).                                                                                                                                                                      
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.  

**Step 3-**
● mpd.service - Music Player Daemon
   Loaded: loaded (/lib/systemd/system/mpd.service; enabled; vendor preset: enabled)                                                                                                                               
   Active: failed (Result: exit-code) since Sat 2019-11-30 14:56:12 EST; 9min ago
     Docs: man:mpd(1)                                                                                                                                                                                              
           man:mpd.conf(5)                                                                                                                                                                                         
           file:///usr/share/doc/mpd/user-manual.html                                                                                                                                                              
  Process: 1252 ExecStart=/usr/bin/mpd --no-daemon $MPDCONF (code=exited, status=127)
 Main PID: 1252 (code=exited, status=127)                                                                                                                                                                          
                                                                                                                                                                                                                   
Nov 30 14:56:12 FPP systemd[1]: Starting Music Player Daemon...                                                                                                                                                    
Nov 30 14:56:12 FPP mpd[1252]: /usr/bin/mpd: error while loading shared libraries: libixml.so.10: cannot open shared object file: No such file or directory                                                        
Nov 30 14:56:12 FPP systemd[1]: mpd.service: Main process exited, code=exited, status=127/n/a                                                                                                                      
Nov 30 14:56:12 FPP systemd[1]: mpd.service: Failed with result 'exit-code'.                                                                                                                                       
Nov 30 14:56:12 FPP systemd[1]: Failed to start Music Player Daemon.
Nov 30 14:56:12 FPP systemd[1]: mpd.service: Start request repeated too quickly.                                                                                                                                   
Nov 30 14:56:12 FPP systemd[1]: mpd.service: Failed with result 'exit-code'.                                                                                                                                       
Nov 30 14:56:12 FPP systemd[1]: Failed to start Music Player Daemon.

**Comment by jcrossbdn** [comment]
Can you run the command:
ldconfig -p | grep libixml
from the command line and let me know what it reports?

I'm not sure why libixml wouldn't have been installed with the mpd/mpc install.
When you installed fpp 3.5.4 did you upgrade from the about page or did you download and install from the fresh sd card image?

**Comment by jcrossbdn** [comment]
@Spankyty 
Can you run the command:
ldconfig -p | grep libixml
from the command line and let me know what it reports?

I'm not sure why libixml wouldn't have been installed with the mpd/mpc install.
When you installed fpp 3.5.4 did you upgrade from the about page or did you download and install from the fresh sd card image?

**Comment by Spankyty** [comment]
It says
**libixml.so.10 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libixml.so.10**

I downloaded and installed the fresh sd card image.

**Comment by jcrossbdn** [comment]
@Spankyty 
I have been researching this and really cannot find a solution that looks good.

If you could try the following commands to see if it happens to fix this (basically a manual full uninstall of all components used by the mpd software that this plugin utilizes):
`sudo apt-get remove -y mpc mpd`
`sudo apt autoremove -y`
`sudo apt-get -y update`
`sudo apt-get -y install mpd mpc`
`sudo reboot`

I have seen this issue before but due to a bunch of factors I ended up just re-imaging the SD card with 3.5.4 and the issue didn't reappear so not sure what is causing it.

With any luck this will purge and force re-install all the libraries needed and hopefully everything will link properly... If not, I'll keep digging into it.

Jason

**Comment by Spankyty** [comment]
Thank you so much this worked! I don't know why it didn't install properly before. I greatly appreciate the help! :D
